# Generated by Django 5.2.7 on 2026-01-25 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classrooms", "0008_announcementattachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityGroupSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_group_set",
                        to="classrooms.classroomactivityassignment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_activity_group_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="activity_groups.activitygroupset",
                    ),
                ),
            ],
            options={
                "ordering": ["group_set", "label"],
            },
        ),
        migrations.CreateModel(
            name="GroupAIRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_reason",
                    models.CharField(
                        choices=[
                            ("submission_summary", "Submission Summary"),
                            ("follow_up_generation", "Follow Up Generation"),
                            ("manual_review", "Manual Review"),
                        ],
                        db_index=True,
                        default="submission_summary",
                        max_length=50,
                    ),
                ),
                ("input_response_ids", models.JSONField(default=list)),
                ("synthesized_summary_text", models.TextField()),
                ("model_name", models.CharField(max_length=100)),
                ("model_params", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_runs",
                        to="activity_groups.activitygroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupAIPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_order", models.PositiveSmallIntegerField()),
                ("prompt_text", models.TextField()),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("follow_up", "Follow Up"),
                            ("reflection", "Reflection"),
                            ("extension", "Extension"),
                            ("check_in", "Check In"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group_ai_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="activity_groups.groupairun",
                    ),
                ),
            ],
            options={
                "ordering": ["group_ai_run", "prompt_order"],
            },
        ),
        migrations.CreateModel(
            name="ActivityGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="activity_groups.activitygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="activity_groups.activitygroupset",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["activity_group"], name="activity_gr_activit_efa2e2_idx"
                    ),
                    models.Index(
                        fields=["user"], name="activity_gr_user_id_072f74_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group_set", "user"),
                        name="unique_group_set_membership_per_user",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="activitygroup",
            index=models.Index(
                fields=["group_set", "archived_at"],
                name="activity_gr_group_s_4b0507_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activitygroup",
            unique_together={("group_set", "label")},
        ),
        migrations.AddIndex(
            model_name="groupairun",
            index=models.Index(
                fields=["activity_group", "created_at"],
                name="activity_gr_activit_55e775_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupaiprompt",
            constraint=models.UniqueConstraint(
                fields=("group_ai_run", "prompt_order"),
                name="unique_prompt_order_per_run",
            ),
        ),
    ]
