# Generated by Django 4.2.16 on 2026-01-28 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0008_announcementattachment'),
        ('activity_groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitygroupset',
            name='assignment',
        ),
        migrations.AddField(
            model_name='activitygroupset',
            name='classroom_activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_group_set', to='classrooms.classroomactivity'),
        ),
    ]
