# Generated by Django 4.2.16 on 2026-01-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_groups', '0002_change_groupset_to_classroom_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupairun',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='When the questions were released to students. Null means not released.', null=True),
        ),
    ]
