# Generated by Django 5.2.7 on 2025-11-10 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0003_enrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_id", models.CharField(max_length=50)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="classrooms.classroom",
                    ),
                ),
            ],
            options={
                "db_table": "classroom_activity",
                "unique_together": {("classroom", "activity_id")},
            },
        ),
    ]
