# Generated by Django 4.2.16 on 2025-12-27 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0005_classroomactivity_assigned_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x_position', models.FloatField(default=0)),
                ('y_position', models.FloatField(default=0)),
                ('rotation', models.FloatField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='classrooms.classroom')),
            ],
            options={
                'db_table': 'classroom_table',
            },
        ),
        migrations.CreateModel(
            name='TableMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_messages', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classrooms.classroomtable')),
            ],
            options={
                'db_table': 'table_message',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='assigned_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classrooms.classroomtable'),
        ),
    ]
