# Generated by Django 5.2.7 on 2025-11-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_id', models.CharField(max_length=50, unique=True)),
                ('activity_title', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_task', models.TextField(blank=True, null=True)),
                ('pe', models.CharField(blank=True, max_length=50, null=True)),
                ('lp', models.CharField(blank=True, max_length=50, null=True)),
                ('lp_text', models.TextField(blank=True, null=True)),
                ('question_1', models.TextField(blank=True, null=True)),
                ('question_2', models.TextField(blank=True, null=True)),
                ('question_3', models.TextField(blank=True, null=True)),
                ('question_4', models.TextField(blank=True, null=True)),
                ('question_5', models.TextField(blank=True, null=True)),
                ('is_released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.FloatField(default=0.1)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': '"public"."science_activity"',
                'managed': False,
            },
        ),
    ]
