# Generated by Django 5.2.7 on 2025-10-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_scienceactivityimages_alter_scienceactivity_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="scienceactivity",
            table='"public"."science_activity"',
        ),
    ]
