# Generated by Django 5.2.7 on 2025-11-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_alter_scienceactivity_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scienceactivityimages",
            options={},
        ),
    ]
