# Generated by Django 5.2.7 on 2025-11-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_alter_scienceactivityimages_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scienceactivityimages",
            options={"managed": False},
        ),
    ]
