# Generated by Django 5.2.7 on 2025-11-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0005_alter_scienceactivityimages_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScienceActivitySubmission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("feedback_overview", models.TextField(blank=True, null=True)),
                ("attempt_number", models.IntegerField(default=1)),
                ("activity_answers", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": '"public"."activity_submissions"',
                "managed": False,
            },
        ),
    ]
