# Generated by Django 4.2.16 on 2026-01-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_scienceactivitysubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_number', models.SmallIntegerField()),
                ('question_text', models.TextField()),
                ('student_answer', models.TextField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"public"."activity_answers"',
                'managed': False,
            },
        ),
    ]
